### ISSUE TITLE
Use the new script system by default

### ISSUE THREAD

**Issue by ccomrade** [ccomrade/crymp-client#20]
Right now, the new script system has to be explicitly enabled with the `-ss` command line parameter. The old CryScriptSystem DLL is used by default. This should change at some point in the future.

**Comment by griseraner** [comment]
Yeah why not... Just have to fix another Sound Script Lua error, appearing on Hotspot (some Hunter crap) then it should work fine

**Comment by ccomrade** [comment]
The new script system is now used always.
